### ISSUE TITLE
[Question] How to setup google feed with different locale?

### ISSUE THREAD

**Issue by jelen07** [Setono/SyliusFeedPlugin#10]
Hi, what is the best way to setup multiple feeds wittin the channel? I'am using 3 locales on one channel. Thanks.

**Comment by loevgaard** [comment]
Hi @jelen07 

Thank you for writing.

I am not quite sure what you mean. Can you give an example of what you want?

**Comment by jelen07** [comment]
Hi @loevgaard,
I was looking for this
![Screenshot from 2019-11-12 14-15-51](https://user-images.githubusercontent.com/2346295/68674902-102e8800-0557-11ea-8ed0-7aaecf187f75.png)

So it's supported by default. That's great!
I was so hurried - testing it on default Sylius installation.

**Comment by loevgaard** [comment]
Cool :)
