### ISSUE TITLE
Normalizer interfering with Sylius 1.8 new api

### ISSUE THREAD

**Issue by LucaGallinari** [Setono/SyliusFeedPlugin#19]
Hi, we were trying the new api system of Sylius 1.8 (that is still under development) and we found out that something in this plugin was changing the responses of these apis. The problem is in the normalizer service (src/Resources/config/services/normalizer.xml):

>         <service id="setono_sylius_feed.normalizer.to_string"
>                  class="Setono\SyliusFeedPlugin\Normalizer\ToStringNormalizer">
>             <tag name="serializer.normalizer"/>
>         </service>

Infact, the responses all contains just the "to string" normalization of the objects. Is it possible to limitate this normalizer only to the purposes of the plugin?

**Comment by loevgaard** [comment]
Hi Luca

I haven't tested 1.8 yet and haven't used API platform. Can you come up with a PR that fixes this? Does it have something to do with the order of normalizers?

**Comment by kayneth** [comment]
Hi! 🙂

I was thinking of maybe using the `context` in the `supportsNormalization` method thanks to [ContextAwareNormalizerInterface](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/ContextAwareNormalizerInterface.php).

That is already what's [API-Platform is using internally](https://api-platform.com/docs/core/serialization/#the-serialization-context-groups-and-relations).

I've been planning to try Sylius 1.8 soon. I'll come back here after that if still needed.

**Comment by loevgaard** [comment]
I used your approach @kayneth. I am not sure if this is the cleanest solution, but it works to not interfere with API Platform :)
