### ISSUE TITLE
Language and structure in the feeds not correct?

### ISSUE THREAD

**Issue by TELLO0815** [Setono/SyliusFeedPlugin#3]
Language for the product name, description, taxon and on... is not changing with the locale like en_US / fr_FR.
The URL´s are correct.

Also the definition-structure of the xml is not correct anymore for google and bing. 

BDW: How can i overwrite the GenerateFeedsCommand.php?

**Comment by TELLO0815** [comment]
Language for the product name, description, taxon and on... is not changing with the locale like en_US / fr_FR.
THe URL´s are correct.

**Comment by loevgaard** [comment]
Closing this, since a lot of work has been done since this :)
