### ISSUE TITLE
Upgrade to Sylius 1.9

### ISSUE THREAD

**Issue by lruozzi9** [Setono/SyliusFeedPlugin#42]
It's impossible to upgrade to Sylius 1.9 using Symfony 5.2 with this plugin installed. This is due to the fact that Symfony 5 requires doctrine 2 and setono/doctrine-orm-batcher-bundle is compatible with doctrine-bundle v1 only.

[Upgrading to DoctrineBundle 2.0
](https://symfonycasts.com/screencast/symfony5-upgrade/doctrine-bundle-2.0#doctrinebundle-amp-symfony-5-compatibility)

**Comment by arjanfrans** [comment]
I'm running into the same problem with this plugin.

**Comment by LucaGallinari** [comment]
There is a PR for this: https://github.com/Setono/SyliusFeedPlugin/pull/46

**Comment by loevgaard** [comment]
The Doctrine ORM Batcher Bundle allows Doctrine bundle v1 or v2: https://packagist.org/packages/setono/doctrine-orm-batcher-bundle

**Comment by loevgaard** [comment]
Closing this for now since I presume the plugin actually supports Sylius ^1.9. If it doesn't please create a new issue with the missing deps
