### ISSUE TITLE
psr/log incompatibility with latest sylius

### ISSUE THREAD

**Issue by aureliusm** [Setono/SyliusFeedPlugin#80]
Hi,

can you please bumb the `psr/log` version to `2.0`, because otherwise this plugin is not usable with the latest version `1.12` of Sylius -> https://github.com/Sylius/Sylius/blob/1.12/composer.json#L68.

Thanks :)

**Comment by loevgaard** [comment]
Please make a PR :)

**Comment by aureliusm** [comment]
Done :) https://github.com/Setono/SyliusFeedPlugin/pull/81
